### PR TITLE
Add Operator

### PR DESCRIPTION
**Pull request by nakajijapan**
I added Operator`<->` in iOS target.

### CODE REVIEW

**Comment by nakajijapan** [comment]
@solidcell 

Could you review this PR?

**Comment by solidcell** [comment]
Ah, good stuff @nakajijapan! I'm a bit busy at the moment (just got back from vacation), but I'll take a look ASAP.

For posterity: https://github.com/ReactiveX/RxSwift/issues/771

**Comment by edopelawi** [comment]
Folks, any update on this PR? Would love to have this on next release!

**Comment by solidcell** [comment]
@nakajijapan I merged your changes plus some other stuff in #11 (`CHANGELOG.md`, example view controller in the example app, etc.).  Thanks again!

**Pull request closed without merging**
